// Code generated by 'yaegi extract github.com/getynge/gofast/lib/gofast/permissions'. DO NOT EDIT.

package extracted

import (
	"github.com/getynge/gofast/lib/gofast/permissions"
	"reflect"
)

func init() {
	Symbols["github.com/getynge/gofast/lib/gofast/permissions/permissions"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AccessSystemPath": reflect.ValueOf(permissions.AccessSystemPath),
		"DownloadScript":   reflect.ValueOf(permissions.DownloadScript),
		"NewPermission":    reflect.ValueOf(permissions.NewPermission),
		"ParseError":       reflect.ValueOf(&permissions.ParseError).Elem(),
		"ParseId":          reflect.ValueOf(permissions.ParseId),
		"Request":          reflect.ValueOf(permissions.Request),

		// type definitions
		"BasePermission": reflect.ValueOf((*permissions.BasePermission)(nil)),
		"Permission":     reflect.ValueOf((*permissions.Permission)(nil)),
	}
}
